In [1]:
from inference_for_handler import SemSeg
from torchvision import io
import torch
import yaml
import matplotlib.pyplot as plt

/home/omnoai/anaconda3/envs/yolov7/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [28]:
with open(r'configs/segformer_custom.yaml') as file:
    cfg = yaml.load(file, Loader=yaml.FullLoader)


In [29]:
model = SemSeg(cfg)
image = io.read_image("data/basketball_train_data/images/validation/v4_00022200.jpg")
img = model.preprocess(image)
seg_map = model.model_forward(img)
seg_map = model.postprocess(img, seg_map, overlay=True)

Original Image Size > 720x1280

Inference Image Size > 512x928

Elapsed time: 14.50ms


In [26]:
seg_map

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]])

In [27]:
torch.unique(seg_map)

tensor([0, 1, 2, 3])

In [5]:
import numpy as np
seg_map = np.array(seg_map)
seg_map.shape

(1, 512, 928)

In [6]:
seg_map = np.reshape(seg_map, (512, 928, 1))
seg_map = seg_map[10:50, 0:10, :]

In [7]:
seg_map.shape

(40, 10, 1)

In [51]:
np.unique(seg_map)

array([0])